name: pipeline

on:
  push:
    branches:
      - staging

jobs:
  test_frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test

  build_frontend:
    runs-on: ubuntu-latest
    needs: test_frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: npm install
      - name: Build project
        run: |
          chmod +x ./deployment/build.sh
          chmod +x ./deployment/deploy.sh
          ./deployment/build.sh
        env:
          APP_BACKEND_API: "https://cart-api/v1.com"
      - name: Move deploy script to dist/ directory
        run: mv -r deployment dist/
      - name: Share artifact with jobs
        uses: actions/upload-artifact@v1
        with:
          name: build-artifact
          path: dist

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - name: Dist artifacts
        uses: actions/download-artifact@v1
        with:
          name: build-artifact
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: deploy application
        working-directory: build-artifact
        run: ./deployment/build.sh
      - name: invalidate s3
        run: ./deployment/build.sh
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
